"""initial schema

Revision ID: a4b93b2d06f0
Revises: 
Create Date: 2026-09-22 12:06:20.037993+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a4b93b2d06f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_timestamp', ['timestamp'], unique=False)

    op.create_table('alerts_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts_log', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_user_type_sent', ['username', 'alert_type', 'sent_at'], unique=False)

    op.create_table('groups',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('shared_quota', sa.Integer(), nullable=True),
    sa.Column('pages_used', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('shared_quota IS NULL OR shared_quota >= 0', name='ck_groups_shared_quota'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('print_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_value', sa.String(length=128), nullable=True),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scope_type IN ('user','group','printer','global')", name='ck_policies_scope_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_policies', schema=None) as batch_op:
        batch_op.create_index('ix_policies_scope', ['scope_type', 'scope_value'], unique=False)

    op.create_table('printers',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('real_device_uri', sa.String(length=512), nullable=True),
    sa.Column('cost_per_page_mono', sa.Float(), nullable=False),
    sa.Column('cost_per_page_color', sa.Float(), nullable=False),
    sa.Column('supports_duplex', sa.Boolean(), nullable=False),
    sa.Column('duplex_discount', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duplex_discount >= 0 AND duplex_discount < 1', name='ck_printers_duplex_discount'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('group_name', sa.String(length=128), nullable=True),
    sa.Column('quota_limit', sa.Integer(), nullable=False),
    sa.Column('pages_used', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('low_balance_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quota_limit >= 0', name='ck_users_quota_limit'),
    sa.ForeignKeyConstraint(['group_name'], ['groups.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_group_name', ['group_name'], unique=False)

    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cups_job_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('printer', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('is_color', sa.Boolean(), nullable=False),
    sa.Column('is_duplex', sa.Boolean(), nullable=False),
    sa.Column('estimated_pages', sa.Integer(), nullable=True),
    sa.Column('actual_pages', sa.Integer(), nullable=True),
    sa.Column('charged_pages', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('allowed','denied','completed','error')", name='ck_jobs_status'),
    sa.ForeignKeyConstraint(['printer'], ['printers.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_printer_job', ['printer', 'cups_job_id'], unique=False)
        batch_op.create_index('ix_jobs_reconciled', ['reconciled', 'status'], unique=False)
        batch_op.create_index('ix_jobs_username_submitted', ['username', 'submitted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_username_submitted')
        batch_op.drop_index('ix_jobs_reconciled')
        batch_op.drop_index('ix_jobs_printer_job')

    op.drop_table('print_jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_group_name')

    op.drop_table('users')
    op.drop_table('printers')
    with op.batch_alter_table('print_policies', schema=None) as batch_op:
        batch_op.drop_index('ix_policies_scope')

    op.drop_table('print_policies')
    op.drop_table('groups')
    with op.batch_alter_table('alerts_log', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_user_type_sent')

    op.drop_table('alerts_log')
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_timestamp')

    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
