"""Configuration loading.

Precedence (highest first):
    1. ``PRINTQUOTA_*`` environment variables
    2. Values saved from the web console (``app_settings`` table), for the
       keys in :data:`RUNTIME_KEYS` only
    3. ``config/settings.yaml`` (path from ``PRINTQUOTA_CONFIG``)
    4. Built-in defaults in :data:`DEFAULTS`

Layer 2 is read through a provider that the database layer registers (see
:func:`register_override_provider`), so this module never imports the ORM.
Anything that decides how a process *reaches* the database or runs --
``database.*``, ``secret_key``, ``api.*``, ``logging.*`` and the CUPS paths
-- is deliberately not in :data:`RUNTIME_KEYS`: it stays file/env only and
is available through :func:`get_base_settings` without touching the
database.

Nothing operational is hardcoded at the call sites; every component reads
its values through :func:`get_settings`.
"""

from __future__ import annotations

import copy
import os
import threading
import time
from functools import lru_cache
from pathlib import Path
from typing import Any, Callable, Optional

import yaml

from .exceptions import ConfigError

DEFAULTS: dict[str, Any] = {
    "database": {"url": "sqlite:///./printquota.db", "echo": False},
    "quota": {
        "default_limit": 500,
        "period_days": 30,
        "default_low_balance_threshold": 50,
        "enforcement": "strict",
        "enforce_group_budget": True,
        "count_two_sided_as_sheets": True,
    },
    "printing": {
        "default_cost_per_page_mono": 1.0,
        "default_cost_per_page_color": 5.0,
        "default_duplex_discount": 0.0,
        "currency": "NGN",
        "real_backend_dir": "/usr/lib/cups/backend",
        "page_log": "/var/log/cups/page_log",
        "spool_dir": "/var/spool/cups",
        "estimator_timeout": 15,
    },
    "alerts": {
        "enabled": True,
        "channel": "email",
        "webhook_url": "",
        "cooldown_hours": 24,
        "smtp": {
            "host": "",
            "port": 25,
            "user": "",
            "password": "",
            "from_address": "printquota@localhost",
            "use_tls": False,
        },
    },
    "api": {
        "host": "0.0.0.0",
        "port": 8080,
        "session_cookie": "printquota_session",
        "session_max_age": 28800,
        "auth_backend": "local",
    },
    "logging": {"level": "INFO", "use_journald": True},
    "secret_key": "",
    #: One-time token that unlocks the browser setup wizard while no
    #: administrator exists. Generated by install.sh.
    "setup_token": "",
}

#: Settings an administrator may change from the web console, with the type
#: each value must have. The console's field definitions live in
#: :mod:`printquota.services.runtime_settings`; a test keeps the two in step.
RUNTIME_KEYS: dict[str, type] = {
    "quota.default_limit": int,
    "quota.period_days": int,
    "quota.default_low_balance_threshold": int,
    "quota.enforcement": str,
    "quota.enforce_group_budget": bool,
    "quota.count_two_sided_as_sheets": bool,
    "printing.default_cost_per_page_mono": float,
    "printing.default_cost_per_page_color": float,
    "printing.default_duplex_discount": float,
    "printing.currency": str,
    "alerts.enabled": bool,
    "alerts.channel": str,
    "alerts.webhook_url": str,
    "alerts.cooldown_hours": int,
    "alerts.smtp.host": str,
    "alerts.smtp.port": int,
    "alerts.smtp.user": str,
    "alerts.smtp.password": str,
    "alerts.smtp.from_address": str,
    "alerts.smtp.use_tls": bool,
}

#: Environment variable -> dotted settings path.
ENV_MAP: dict[str, str] = {
    "PRINTQUOTA_DB_URL": "database.url",
    "PRINTQUOTA_DB_ECHO": "database.echo",
    "PRINTQUOTA_SECRET_KEY": "secret_key",
    "PRINTQUOTA_LOG_LEVEL": "logging.level",
    "PRINTQUOTA_PAGE_LOG": "printing.page_log",
    "PRINTQUOTA_REAL_BACKEND_DIR": "printing.real_backend_dir",
    "PRINTQUOTA_SPOOL_DIR": "printing.spool_dir",
    "PRINTQUOTA_SMTP_HOST": "alerts.smtp.host",
    "PRINTQUOTA_SMTP_PORT": "alerts.smtp.port",
    "PRINTQUOTA_SMTP_USER": "alerts.smtp.user",
    "PRINTQUOTA_SMTP_PASSWORD": "alerts.smtp.password",
    "PRINTQUOTA_SMTP_FROM": "alerts.smtp.from_address",
    "PRINTQUOTA_API_HOST": "api.host",
    "PRINTQUOTA_API_PORT": "api.port",
    "PRINTQUOTA_AUTH_BACKEND": "api.auth_backend",
    "PRINTQUOTA_SETUP_TOKEN": "setup_token",
}

_CONFIG_SEARCH = (
    "/etc/printquota/settings.yaml",
    "config/settings.yaml",
)

_TRUE = {"1", "true", "yes", "on"}
_FALSE = {"0", "false", "no", "off"}


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    out = copy.deepcopy(base)
    for key, value in (override or {}).items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = _deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def _coerce(existing: Any, raw: str) -> Any:
    """Coerce an environment string to the type of the default it replaces."""
    if isinstance(existing, bool):
        low = raw.strip().lower()
        if low in _TRUE:
            return True
        if low in _FALSE:
            return False
        raise ConfigError(f"expected a boolean, got {raw!r}")
    if isinstance(existing, int) and not isinstance(existing, bool):
        return int(raw)
    if isinstance(existing, float):
        return float(raw)
    return raw


def _set_path(data: dict[str, Any], dotted: str, raw: str) -> None:
    parts = dotted.split(".")
    node = data
    for part in parts[:-1]:
        node = node.setdefault(part, {})
    leaf = parts[-1]
    node[leaf] = _coerce(node.get(leaf), raw)


class Settings:
    """Read-only view over the merged configuration tree."""

    def __init__(self, data: dict[str, Any], source: str | None = None) -> None:
        self._data = data
        self.source = source

    def get(self, dotted: str, default: Any = None) -> Any:
        """Return a value by dotted path, e.g. ``quota.period_days``."""
        node: Any = self._data
        for part in dotted.split("."):
            if not isinstance(node, dict) or part not in node:
                return default
            node = node[part]
        return node

    def require(self, dotted: str) -> Any:
        value = self.get(dotted, None)
        if value in (None, ""):
            raise ConfigError(f"required setting {dotted!r} is not set")
        return value

    def section(self, name: str) -> dict[str, Any]:
        value = self.get(name, {})
        return copy.deepcopy(value) if isinstance(value, dict) else {}

    def as_dict(self) -> dict[str, Any]:
        return copy.deepcopy(self._data)

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<Settings source={self.source!r}>"


def _locate_config(path: str | os.PathLike[str] | None) -> Path | None:
    if path:
        candidate = Path(path)
        if not candidate.is_file():
            raise ConfigError(f"config file not found: {candidate}")
        return candidate
    env_path = os.environ.get("PRINTQUOTA_CONFIG")
    if env_path:
        candidate = Path(env_path)
        if not candidate.is_file():
            raise ConfigError(f"PRINTQUOTA_CONFIG points at a missing file: {candidate}")
        return candidate
    for name in _CONFIG_SEARCH:
        candidate = Path(name)
        if candidate.is_file():
            return candidate
    return None


def _file_layer(path: str | os.PathLike[str] | None = None) -> tuple[dict[str, Any], Optional[Path]]:
    """Defaults deep-merged with the YAML file (no overrides, no environment)."""
    config_path = _locate_config(path)
    data = copy.deepcopy(DEFAULTS)
    if config_path is not None:
        try:
            loaded = yaml.safe_load(config_path.read_text()) or {}
        except yaml.YAMLError as exc:  # pragma: no cover - malformed file
            raise ConfigError(f"could not parse {config_path}: {exc}") from exc
        if not isinstance(loaded, dict):
            raise ConfigError(f"{config_path} must contain a YAML mapping")
        data = _deep_merge(data, loaded)
    return data, config_path


def _put(data: dict[str, Any], dotted: str, value: Any) -> None:
    parts = dotted.split(".")
    node = data
    for part in parts[:-1]:
        node = node.setdefault(part, {})
    node[parts[-1]] = value


def env_overridden_keys() -> set[str]:
    """Dotted keys currently pinned by a non-empty environment variable."""
    return {dotted for env_name, dotted in ENV_MAP.items() if os.environ.get(env_name)}


def _build(
    file_data: dict[str, Any], config_path: Optional[Path], overrides: Optional[dict[str, Any]]
) -> Settings:
    data = copy.deepcopy(file_data)
    for dotted, value in (overrides or {}).items():
        # Only whitelisted keys may come from the database, whatever is stored.
        if dotted in RUNTIME_KEYS:
            _put(data, dotted, value)
    for env_name, dotted in ENV_MAP.items():
        raw = os.environ.get(env_name)
        if raw is not None and raw != "":
            _set_path(data, dotted, raw)
    return Settings(data, source=str(config_path) if config_path else "defaults")


def load_settings(
    path: str | os.PathLike[str] | None = None, overrides: Optional[dict[str, Any]] = None
) -> Settings:
    """Build a :class:`Settings` from defaults, YAML file, overrides and environment."""
    file_data, config_path = _file_layer(path)
    return _build(file_data, config_path, overrides)


@lru_cache(maxsize=1)
def _cached_file_layer() -> tuple[dict[str, Any], Optional[Path]]:
    return _file_layer()


def get_base_settings() -> Settings:
    """Settings from defaults, file and environment only -- never the database.

    Used for everything needed *before* the database can be read (its URL,
    logging) so that loading settings can never recurse into the database.
    """
    file_data, config_path = _cached_file_layer()
    return _build(file_data, config_path, None)


#: Callable returning ``{dotted_key: value}`` saved from the console.
_override_provider: Optional[Callable[[], dict[str, Any]]] = None
#: How long a process trusts its cached overrides. The CUPS backend is a new
#: process per job so it always reads fresh values; the long-running daemon
#: picks up a console change within this window.
OVERRIDE_TTL_SECONDS = 15.0
_lock = threading.RLock()
_local = threading.local()
_cache: dict[str, Any] = {"settings": None, "at": 0.0}


def register_override_provider(provider: Optional[Callable[[], dict[str, Any]]]) -> None:
    """Install the function that reads console-saved settings."""
    global _override_provider
    _override_provider = provider
    invalidate_settings()


def invalidate_settings() -> None:
    """Forget cached overrides so the next :func:`get_settings` re-reads them."""
    with _lock:
        _cache["settings"] = None
        _cache["at"] = 0.0


def get_settings() -> Settings:
    """Process-wide settings, including console-saved overrides."""
    if getattr(_local, "loading", False):
        # Re-entered while the provider itself is reading the database.
        return get_base_settings()
    with _lock:
        cached = _cache["settings"]
        if cached is not None and time.monotonic() - _cache["at"] < OVERRIDE_TTL_SECONDS:
            return cached
    file_data, config_path = _cached_file_layer()
    overrides: dict[str, Any] = {}
    if _override_provider is not None:
        _local.loading = True
        try:
            overrides = _override_provider() or {}
        except Exception:  # pragma: no cover - an unreadable table must never stop printing
            overrides = {}
        finally:
            _local.loading = False
    settings = _build(file_data, config_path, overrides)
    with _lock:
        _cache["settings"] = settings
        _cache["at"] = time.monotonic()
    return settings


def reset_settings_cache() -> None:
    """Drop all cached settings (used by tests and by the CLI ``--config``)."""
    _cached_file_layer.cache_clear()
    invalidate_settings()
